#!/bin/bash
# Quick fix script reference for Render IPv6 connection issue

echo "=========================================="
echo "RENDER DATABASE CONNECTION FIX"
echo "=========================================="
echo ""
echo "YOUR ACTION REQUIRED:"
echo "1. Open Render Dashboard: https://dashboard.render.com"
echo "2. Select service: customer-db-api"
echo "3. Go to Environment tab"
echo "4. Update DATABASE_URL to:"
echo ""
echo "postgresql://postgres.pbbkfqitjsaquaelwbsu:-sA%21%3FWN%3E%2C025@aws-0-us-east-1.pooler.supabase.com:6543/postgres"
echo ""
echo "=========================================="
echo "KEY CHANGES:"
echo "  ✓ Uses AWS pooler (IPv4-only)"
echo "  ✓ Host: aws-0-us-east-1.pooler.supabase.com"
echo "  ✓ Port: 6543 (Transaction Mode)"
echo "  ✓ Password URL-encoded"
echo "=========================================="
echo ""
echo "After saving, Render will auto-redeploy (2-3 minutes)"
echo ""
echo "Verify with:"
echo "  curl https://customer-db-api.onrender.com/health"
echo ""
echo "Full details: docs/05-operations/RENDER_FIX_IPV6.md"
echo "=========================================="
